services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    image: cowcalftracker-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING}
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: cowcalftracker-postgres
    environment:
      POSTGRES_DB: cowcalftracker
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - cowcalftracker_postgres_data:/var/lib/postgresql

volumes:
  cowcalftracker_postgres_data: