// <auto-generated />
using System;
using CowCalfTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CowCalfTracker.Infrastructure.Migrations
{
    [DbContext(typeof(CowCalfTrackerDbContext))]
    [Migration("20260614205451_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CowCalfTracker.Domain.Cattle.Cow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("TagNumber")
                        .HasColumnType("integer")
                        .HasColumnName("tag_number");

                    b.HasKey("Id");

                    b.HasIndex("TagNumber")
                        .IsUnique();

                    b.ToTable("cows", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
